spring:
  application:
    name: hooxi-event-ingestion
  webflux:
    base-path: /ingest/api/v1
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hooxi?schema=hooxi
    username: hooxi
    password: hooxi#123
  data:
    r2dbc:
      repositories:
        enabled: true
    #cassandra:
    #  local-datacenter: datacenter1
    #  keyspace-name: hooxi
  #kafka:
  #  producer:
  #    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #    key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #  properties:
  #    "[spring.json.trusted.packages]": "com.hooxi.event.ingestion.data.model"
  #    "[spring.json.add.type.headers]": false
  #  bootstrap-servers: localhost:29092
hooxi_event_topic: hooxi_event_topic
grpc:
  port: 9090
  shutdownGrace: 30
logging:
  level:
    com.hooxi: DEBUG
server:
  port: 11000
management:
  endpoint:
    health:
      enabled: true
  server:
    port: 11001

hooxi:
  persistence: postgres
  config:
    server:
      url: http://localhost:12000/