spring:
  application:
    name: hooxi-config-server
  main:
    allow-bean-definition-overriding: true
  webflux:
    base-path: /config/api/v1
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hooxi?schema=hooxi
    username: hooxi
    password: hooxi#123
logging:
  level:
    com:
      hooxi: debug
    org:
      springframework: debug
      springdoc: info
    io:
      lettuce: info
server:
  port: 12000
management:
  endpoint:
    health:
      enabled: true
  server:
    port: 12001


