apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - http:
      paths:
        - path: /config/api/v1
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.service.serviceName }}
              port:
                number: 12000